### ISSUE TITLE
Plugin broken in latest Sketch

### ISSUE THREAD

**Issue by custa1200** [ImageOptim/Sketch-plugin#7]
I wrote up the initial bug over on the Mac App Issues list. Probably should have been here. I have at least linked to it as it has images etc already.

https://github.com/ImageOptim/ImageOptim/issues/352

**Comment by kornelski** [comment]
Please talk to Sketch support about this. I think they've broke it on their side. Their [developer docs](https://developer.sketch.com/plugins/) have no mention of any changes for plug-in authors in v73, so this is probably **a Sketch bug**, not something that I can fix.

**Comment by ahenriksen-inferno** [comment]
I have the same issue.

**Comment by craigerskine** [comment]
@kornelski This is what Sketch told me about the issue:

> Thanks for contacting us and for sharing your screenshots. I'm sorry to hear you're having trouble using the ImageOptim plugin with newer Sketch versions.
>
> I tested the plugin and reviewed the Github issue you shared. Like you mention, ImageOptim works fine up to version 75. I also noticed that ImageOptim's last update was done in 2017, so it is possible we are dealing with a version of ImageOptim that is no longer compatible with the latest Sketch versions. In this case I recommend contacting again the plugin developer and ask to take a look considering the date of the plugin's last commit (2017).
>
> I'm really sorry this falls outside my field of action. My apologies for the inconveniences caused. Please let me know if you have any further questions about this or any other matter.

**Comment by kornelski** [comment]
So we have an impasse here. The fact that I haven't changed in the plug-in since 2017 to me means that I couldn't have broken anything recently. 

If the plug-in worked in v75, and doesn't in v76, that means Sketch has broken something. Maybe they have dropped support for some old API, but the problem is: **Sketch has not documented any breaking changes in v76**. Their docs end at v72. So by Sketch's documentation, every plug-in that works with v75 is supposed to work with v76.

I'm happy to change what they want, but they need to document what needs to be changed.

**Comment by craigerskine** [comment]
Looks like v78 magically fixed the issue. ImageOptim is now working for me in Sketch v78.
